spring.application.name=MonoPat
# Configuración inteligente: Si existe la variable en Render la usa, si no, usa localhost
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/monopat_db}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:}
monopat.reserva.tarifa-por-minuto=300
server.port=${PORT:8080}