spring.application.name=MonoPat
spring.datasource.url=jdbc:mysql://localhost:3306/monopat_db
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.datasource.username=root
spring.datasource.password=!Andres123
monopat.reserva.tarifa-por-minuto=300